### ISSUE TITLE
Add Psi Support

### ISSUE THREAD

**Issue by chris-chambers** [sbbm/sbbm#11]
This is a tracking issue for psi support.  Robust predication support is going to be needed to handle the peculiarities of Minecraft/SBBM.

To get there, we need:
- [x] Add Psi Instruction #12
- [x] Add PsiElimination pass (at first, as an SBBM-only pass) #13
- [x] Write a new if-conversion pass that runs before register allocation and uses psi instructions to perform predication. #14

**Comment by chris-chambers** [comment]
This should have been opened in sbbm/llvm instead. (See: sbbm/llvm#9).
